version: '3.8'
services:
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - jsramverk-mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changeme
      - MONGO_INITDB_DATABASE=jsramverk

volumes:
  jsramverk-mongodb-data:
