name: Test backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      dir: ./api

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ${{env.dir}}
        run: npm install

      - name: Run tests
        working-directory: ${{env.dir}}
        run: npm run test

      - name: Deploy coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: api/coverage/lcov-report
          target-folder: api-coverage
          commit-message: 'docs(api): coverage report'
